### ISSUE TITLE
remove your twitter credentials

### ISSUE THREAD

**Issue by natebrennand** [anshulkgupta/The-Indian-Voter#1]
You should keep any file with auth settings in your `.gitignore`.

Unfortunately github makes is super easy to search through code for credentials...

**Comment by anshulkgupta** [comment]
Yep, noticed this yesterday. Unfortunately, I'm running out of time to get
the project wrapped up (really wanted to get it done this past weekend). I
spent over 20 hours this weekend -- entire Saturday and last night.

But atleast I got the database up! Now it just keeps crashing so I'm trying
to either schedule a cron job or put in enough error handling code. I'll
look into this later today and fix it!

Thanks a ton for catching this though.

---

_Anshul Gupta_

www.anshulkgupta.com

**Comment by anshulkgupta** [comment]
lol what i newbie i was (am!)
